# Generated by Django 2.2.6 on 2019-10-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linuxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
